### ISSUE TITLE
What is the current situation of SvelteKit, is it production ready?

### ISSUE THREAD

**Issue by projektorius96** [JVariance/SvelteKit-x-Neutralino#1]
Just wondering what is your point of view to the question given . Cheers !

**Comment by JVariance** [comment]
I guess I am not the most advanced developer and I am not really experienced in the framework territory so my oppinion carries not a lot weight.
Angular was the first framework I tried, but I couldn't use SVGs like I wanted. React just looked to complicated, I had no joy trying it out. I never tried Vue as I tried Svelte next and fell in love with it. I am also really happy with SvelteKit, but this may be because I don't know anything to miss from other frameworks 😃
